backend:
  name: test-repo

media_folder: "public/assets/images"
public_folder: "/assets/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/content/config.ts"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Hero Title", name: "title", widget: "string" }
          - { label: "Hero Subtitle", name: "subtitle", widget: "text" }
          - { label: "Banner Image", name: "image", widget: "image" }
